### ISSUE TITLE
Support for Chromium-based browsers

### ISSUE THREAD

**Issue by ivanhercaz** [maxlath/maximize-telegram-web#1]
Hi @Maxlath!

Simple but very useful extension. I use Brave as my main browser, so I am interested in something similar for Chromium-based browsers.

I think it isn't something very complicated, so I could make by myself. But I have a doubt, should I create a separated repository for the Chromium-based extension or could it be in this repository?

I await your answer. Thank you for your work!

**Comment by maxlath** [comment]
I just published on Chrome Store, I will let you know when it has been validated :)

**Comment by maxlath** [comment]
@ivanhercaz it's online! https://chrome.google.com/webstore/detail/maximize-telegram-web/mbhckhjkdehemegdjaoajolbenoamcpf

**Comment by ivanhercaz** [comment]
Thank you very much! I am going to install just now. I consider this issue is fixed so I am going todo close it.
